"""syka

Revision ID: 7a4302562b8b
Revises: 
Create Date: 2024-09-24 15:07:04.416066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4302562b8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('register_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('examinations',
    sa.Column('id_examination', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name_file', sa.String(), nullable=False),
    sa.Column('loading_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('number_of_errors', sa.Integer(), nullable=False),
    sa.Column('course_compliance', sa.Integer(), nullable=False),
    sa.Column('download_link_source', sa.String(), nullable=False),
    sa.Column('download_link_edited', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_examination')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examinations')
    op.drop_table('users')
    # ### end Alembic commands ###
