"""писание изменений

Revision ID: 8aaff62a30d0
Revises: 222d0d07d0ab
Create Date: 2025-04-08 19:45:14.438262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aaff62a30d0'
down_revision: Union[str, None] = '222d0d07d0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # Проверяем существование индексов перед созданием
    inspector = sa.inspect(op.get_bind())
    
    # Изменение колонок
    op.alter_column('blacklisted_tokens', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # Для blacklisted_on
    op.alter_column('blacklisted_tokens', 'blacklisted_on',
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(),
            existing_nullable=True,
            postgresql_using='blacklisted_on::timestamp')


    
    # Создаем индексы только если они не существуют
    indexes = inspector.get_indexes('blacklisted_tokens')
    if not any(idx['name'] == 'ix_blacklisted_tokens_id' for idx in indexes):
        op.create_index(op.f('ix_blacklisted_tokens_id'), 'blacklisted_tokens', ['id'], unique=False)
    if not any(idx['name'] == 'ix_blacklisted_tokens_token' for idx in indexes):
        op.create_index(op.f('ix_blacklisted_tokens_token'), 'blacklisted_tokens', ['token'], unique=True)
    
    # Остальные изменения
    op.alter_column('examinations', 'loading_at',
           existing_type=sa.VARCHAR(),
           type_=sa.DateTime(),
           existing_nullable=True,
           postgresql_using='loading_at::timestamp')
    # Для course_compliance
    op.alter_column('examinations', 'course_compliance',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using='course_compliance::integer')
    # Для last_active
    op.alter_column('examinations', 'last_active',
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(),
            existing_nullable=True,
            postgresql_using='last_active::timestamp')
    
    indexes = inspector.get_indexes('examinations')
    if not any(idx['name'] == 'ix_examinations_id_examination' for idx in indexes):
        op.create_index(op.f('ix_examinations_id_examination'), 'examinations', ['id_examination'], unique=False)
    if not any(idx['name'] == 'ix_examinations_last_active' for idx in indexes):
        op.create_index(op.f('ix_examinations_last_active'), 'examinations', ['last_active'], unique=False)
    
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    indexes = inspector.get_indexes('users')
    if not any(idx['name'] == 'ix_users_email' for idx in indexes):
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    if not any(idx['name'] == 'ix_users_id_user' for idx in indexes):
        op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    if not any(idx['name'] == 'ix_users_username' for idx in indexes):
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    op.drop_column('users', 'register_at')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('register_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_examinations_last_active'), table_name='examinations')
    op.drop_index(op.f('ix_examinations_id_examination'), table_name='examinations')
    op.alter_column('examinations', 'last_active',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('examinations', 'course_compliance',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('examinations', 'loading_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_blacklisted_tokens_token'), table_name='blacklisted_tokens')
    op.drop_index(op.f('ix_blacklisted_tokens_id'), table_name='blacklisted_tokens')
    op.alter_column('blacklisted_tokens', 'blacklisted_on',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('blacklisted_tokens', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
