"""Add errors column to examinations

Revision ID: 9ca68d5ae2b3
Revises: 7a4302562b8b
Create Date: 2024-11-02 00:22:10.883050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ca68d5ae2b3'
down_revision: Union[str, None] = '7a4302562b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinations', sa.Column('errors', sa.String(), nullable=True))
    op.alter_column('examinations', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('examinations', 'name_file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('examinations', 'loading_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('examinations', 'number_of_errors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('examinations', 'course_compliance',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('examinations', 'download_link_source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('examinations', 'download_link_edited',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('examinations_id_user_fkey', 'examinations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('examinations_id_user_fkey', 'examinations', 'users', ['id_user'], ['id_user'])
    op.alter_column('examinations', 'download_link_edited',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('examinations', 'download_link_source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('examinations', 'course_compliance',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('examinations', 'number_of_errors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('examinations', 'loading_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('examinations', 'name_file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('examinations', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('examinations', 'errors')
    # ### end Alembic commands ###
