"""Добавление или изменение столбца

Revision ID: 222d0d07d0ab
Revises: 9ca68d5ae2b3
Create Date: 2024-11-02 01:42:52.945431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222d0d07d0ab'
down_revision: Union[str, None] = '9ca68d5ae2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
